### ISSUE TITLE
Document REQUESTS_MAX_RETRIES

### ISSUE THREAD

**Issue by jacobwegner** [django-salesforce/django-salesforce#159] opened 2016-07-20 18:17 UTC
The [`REQUESTS_MAX_RETRIES`](https://github.com/django-salesforce/django-salesforce/blob/3597d1dcb0f3fea377a1d32f9fc0e554a9dd5759/salesforce/backend/__init__.py#L31) setting is used to retry failed requests.

I saw an issue when creating new SObjects where a `ReadTimeoutError` occurred while connecting to the SalesForce API.

The SObject was created on SalesForce's side, but requests retried the request ([as expected](https://github.com/kennethreitz/requests/blob/9e9d2c6521e37e1c4f35e04f95a910ad47e28958/requests/adapters.py#L88)), which resulted in a duplicate SObject being created in SalesForce.

I'd like to see `REQUESTS_MAX_RETRIES` documented, and perhaps differing behavior between retrying GET requests, but not retrying POST/PUT/DELETE requests automatically in the SalesForce database backend.

I've changed `REQUESTS_MAX_RETRIES` to `0` in all of my projects using `django-salesforce` (which is also the [default in requests](https://github.com/kennethreitz/requests/blob/9e9d2c6521e37e1c4f35e04f95a910ad47e28958/requests/adapters.py#L47))

**Comment by hynekcer** [comment] 2016-07-21 09:11
The problem is not possible "occurred while connecting". You probably mean "after connecting" - see the long text below. (Thank you very much for your patch two years ago.)

PUT and DELETE requests can be also safely retried because a retried PUT doesn't change anything and a retried DELETE can't fail since its implementation is equivalent to `DELETE  FROM SObjectType WHERE Id = '...'`.

The repeated POST request is a problem that should be analysed with more arguments: Compared to the default in Requests package, Django is a server framework and a good behavior after long inactivity is more important than for a general tool or a command line utility. The problem is a timeout caused by a broken connection after a long inactivity, where the reset packet has been lost, e.g. because some other layer/device between had been earlier considered the connection inactive. (firewall connection tracking) (More frequent in development than in production.)

A duplicity can be created only if the request header packet passed and ACK received, the body with sObject data has been also passed, but the response header (with return code) or the response body (with the new `Id`) failed. (The ACK for the request body is usually in the response header, it is probably not a special case.) Known broken connections are handled by requests package correctly. It is also not a special case.

The failed request with REQUESTS_MAX_RETRIES=0 would be probably also for you more frequent than the duplicate record with REQUESTS_MAX_RETRIES=1. The question is whether the more frequent is worse, why and when.

A duplicate can be usually easier fixed later than a data loss. What does the user when (s)he receives an error message? Go away or retry all. Even with REQUESTS_MAX_RETRIES=0 you have the same probability that you have by one record more even if think after the exception that nothing has been created. This probability is very low after a long inactivity and guesstimated 50% if the server is somewhat busy.

A small advantage after an exception is that you can know about the uncertainty (inserted or not?), but can not resolve it in the same request.

You can see the previous issue #42 and discussion about the same. I had also reported an issue to Requests and tried a patched Requests and wait long time for their solution before we closed our issue. A useful timeout for request header is useful to be short and the retry is very useful (the fail is very probable and a fast ACK should be expected with some possible protocol level handshake retries and there is no risk of duplicity) The request body should operate also with a short timeout but the retry is by 50% undesirable. The response should operate with a long timeout especially for queries and the retry is completely undesirable, but we need to know the new created ID, otherwise orphans are created. The simply answered that all should be solved by a lower layer, if I remember.

I know a case where the a repeat is really terrible.
Imagine that you have a smart merchandise Order system with an acknowledgement as the second step. You create an order, add order items and finally the order should be confirmed to be complete, otherwise it should be ignored.
- Autorepeat in this step is save and only the last Order could be valid, all duplicates will be automatically ignored.
- Autorepat in OrderItem part is deadly.
- Autorepeat in the acknowledgement part is crucial, since you must definitely know with very high probability whether the Order has been confirmed or not. False positive and false negative would be a big problem.

An important solution for a POST request with retries zero after a longer inactivity is to implement a "ping" request (a fast empty request before). I did not commit it because it seems nobody has had a problem last two years.

It should be documented, but how?  - A complicated description would look like that django-salesforce is a worse then other packages or that the REST API is worse than SOAP API, but the problem is the same and mostly ignored. Every information about it, except a trivial that this setting exists, is invalid by some point of view or so complicated that it is useless.

**Comment by philchristensen** [comment] 2016-07-27 16:08
Closing this issue, but added a link to it from the wiki here under important issues:

https://github.com/django-salesforce/django-salesforce/wiki#important-issues

**Closed by philchristensen** 2016-07-27 16:08 UTC
Labels: discussion, question

**Comment by hynekcer** [comment] 2016-07-28 11:42
I prefer to keep an eye on. My post was more an outline of solution for me than an clear explanation. It is also very new.

I wrote about a possible case "Autorepat in OrderItem part is deadly." That is very serious because even in the case where the developer pay attention and adds a confirm step to the user interface, the result could be invalid and the end user rightfully arraged.
