### ISSUE TITLE
Django `SystemCheck` fails on KeyError `CharField` with PostgreSQL

### ISSUE THREAD

**Issue by piotrpawlaczek** [django-salesforce/django-salesforce#299] opened 2021-12-03 17:15 UTC
I run into the following issue when upgrading to `django3.2`

django-salesforce: `4.0` and `3.2`
django: `3.2.9`

Reproducible with cmd:
```shell
>> ./manage.py check
```

Skippable with cmd:
```shell
>> ./manage.py shell_plus --skip-checks
```

Traceback
```python
>> ./manage.py check

Traceback (most recent call last):
  File "src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/virtualenv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/virtualenv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/virtualenv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/virtualenv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/virtualenv/lib/python3.8/site-packages/django/core/management/commands/check.py", line 63, in handle
    self.check(
  File "/virtualenv/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/virtualenv/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/virtualenv/lib/python3.8/site-packages/django/core/checks/model_checks.py", line 34, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/virtualenv/lib/python3.8/site-packages/django/db/models/base.py", line 1271, in check
    *cls._check_fields(**kwargs),
  File "/virtualenv/lib/python3.8/site-packages/django/db/models/base.py", line 1382, in _check_fields
    errors.extend(field.check(**kwargs))
  File "/virtualenv/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2459, in check
    *super().check(**kwargs),
  File "/virtualenv/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1773, in check
    *super().check(**kwargs),
  File "/virtualenv/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 203, in check
    *self._check_validators(),
  File "/virtualenv/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 349, in _check_validators
    for i, validator in enumerate(self.validators):
  File "/virtualenv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/virtualenv/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1795, in validators
    min_value, max_value = connection.ops.integer_field_range(internal_type)
  File "/virtualenv/lib/python3.8/site-packages/django/db/backends/base/operations.py", line 625, in integer_field_range
    return self.integer_field_ranges[internal_type]
KeyError: 'CharField'
```

After some debugging, it points to:
```python
{'self': <salesforce.models_extend.SfCharAutoField: id>, 'validators_': [], 'internal_type': 'CharField', '__class__': <class 'django.db.models.fields.IntegerField'>}
```

There is clearly a mismatch between `internal_type` and `__class__` type and `CharField` is not a member of `integer_field_ranges`.

Possible solutions I can think of:

Would it be possible to alter `internal_type` from `salesforce.models_extend.SfCharAutoField` to return `AutoField`?

**Comment by hynekcer** [comment] 2021-12-04 16:13
I can not eproduce the problem. Please write a complete minimal example useful to reproduce it especially "models.py" with one model only with only a primary key and "settings.py" without any private data and with short INSTALLED_APPS. I guess that you use "django-extensions". Try if it important to reproduce the error. Share a URL an example.

The primary key of a SalesforceModel should be a string because it isrequired by Salesforce, not an integer. The same is useful even if you want to run fast tests of a Salesforce application with an in-memory Sqlite3 database (possible under some circumstances).

The best is to not specify the primary key explicitly and to let django-salesforce to create it. Have you a reason why it is not possible?

**Comment by piotrpawlaczek** [comment] 2021-12-06 18:06
Afaik this is not related to the primary keys set explicitly, I leave for `django-salesforce` to create them.

I am posting here the URL that points to my repo with a complete, minimal example that can be helpful with reproducing the problem:
https://github.com/piotrpawlaczek/salesforce-bug

**Comment by hynekcer** [comment] 2021-12-07 01:22
Thanks for the example. The information about Postgresql was essential. The issue with `models_extend` is difficult. A similar idea of UUIDAutoField that is not an integer was rejected by a Django team member Nick Pope in [Django ticket # 32577](https://code.djangoproject.com/ticket/32577#comment:11).
The recommend to write an explicit primary key in the model if the type is not compatible with integer.
```python
lass MyModel(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
```

The module `models_extend` (which allows to save Salesforce data in another database and to run tests) still works with Sqlite3. Maybe it will be also broken by some new Django version if they would be more strict. Did you think about sponsorship if you like django-salesforce?

I'm surprised that your patch works for you, because if it works satisfying then you probably don't need to use SalesforceModel from "models_extend.py" and you can use "models.py". What are your main reasons why you use that module?

**Comment by stefanfoulis** [comment] 2021-12-07 09:26
@hynekcer regarding sponsoring, sorry for the long delay. We spoke about my employer sponsoring you a long time ago but never quite got it done. We're now a sponsor 🥳.

**Comment by hynekcer** [comment] 2021-12-07 20:01
Fortunately the fix was not too complicated. I added empty validators to override integer validators from the base type. This was not a problem with Sqlite3 because it has only one integer type and it is not necessary to initialize integer min/max values customized by subtype in Sqlite3. I also added `editable=False` to be clear that primary key is not editable and wherefore doesn't need an extra validator. It is only for a possible case that `auto_created=True` will be not supported by some future version of Django. Currently it is a consequence of other options and it is not needed explicitly.

You are right that your solution works with PostgreSQL, but only with it. My solution works also with SQLite also corresponds better to Django team's recommendations because everything with non Salesforce backends is like a UUIDField. Almost everything related to Salesforce backend (where AutoField is still used) can be easier fixed here in a case of conflict with future Django.

It is fine that a copy/backup of Salesforce data can run now under PostgreSQL. It can be used e.g. for some more complicated analytic SQL queries not supported by SFDC. I don't need it. A simple live SQLite database file is good enough for me and still better than only read a zipped backup of csv files.

Thanks for your sponsorship. If you want a stable support for PostgreSQL then I can do it and write tests for it and run them regularly during development and look sometimes in Postgres code in a case of doubts. It is extra work and I can do it for additional one-time sponsorship that is in "One-time" sponsorship tier tab.

**Comment by hynekcer** [comment] 2021-12-07 21:45
You can also add a line to your application setting to prevent this warning about a non default AutoField:

>  Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.  
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the SalesforceModelsConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.

```python
# your_application.apps.py
...
class SalesforceModelsConfig(AppConfig):
    ...
    default_auto_field = "salesforce.models_extend.SfCharAutoField"
```
I did not described it in documentation because without `AppConfig`  it could configured only globally, which is frequently not acceptable.

**Comment by hynekcer** [comment] 2021-12-20 08:59
Closing because fixed two weeks ago.

**Comment by piotrpawlaczek** [comment] 2022-01-12 16:32
@hynekcer thank you for the fix, I think that overriding the validators from the base type is the correct solution. I wonder whether we should leave it empty though. What about falling back to original validators from dj `CharField`?

https://github.com/django/django/blob/0ed2919814c80e31626dffdb6b80d0c20d43452f/django/db/models/fields/__init__.py#L1014

**Comment by hynekcer** [comment] 2022-01-12 23:56
> ... overriding the validators from the base type is the correct solution.

The **base type** of a primary key in `salesforce.models_extend.SalesforceModel` is currently `django.db.models.fields.AutoField` that is a descendant of `IntegerField`. It is compatible with normal databases and it is really an IntegerField in `salesforce.models.SalesforceModel` with normal non Salesforce databases. I don't want to change the base type without a serious reason.

A validator from a **similar type** (CharField) could be used if you write a correct PR. It is not easy to write a useful validator for Salesforce primary keys because the only important rule is: "Never modify a primary key to something that doesn't exist in Salesforce yet". Primary keys are not editable in Django. Sqlite has no validator for primary keys. PostgreSQL initializes boundary values for an integer validator, but I think that it is usually superfluous and probably never used. Try it please first.

**Comment by piotrpawlaczek** [comment] 2022-01-26 13:40
@hynekcer 
I've been testing the master branch in our setup `pip -e git+https://github.com/django-salesforce/django-salesforce@main#egg=django-salesforce` and everything works like a charm. I don't think anything more is needed.

**Closed** 2022-02-10 21:21 UTC
Labels: bug, edge case
