### ISSUE TITLE
Salesforce router causing issues with migrations

### ISSUE THREAD

**Issue by pbriet** [django-salesforce/django-salesforce#226] opened 2019-03-15 14:42 UTC
Hi,

Let's start by thanking everyone working on this project : great work!

This is my first issue with the library : i'm doing some completely unrelated work in an other database (MySQL), including renaming some models.
When I apply the migrations, I have a crash. It comes from the Salesforce router

```
  File "python3.5/site-packages/django/db/utils.py", line 291, in allow_migrate
    allow = method(db, app_label, **hints)
  File "python3.5/site-packages/salesforce/router.py", line 65, in allow_migrate
    model = apps.get_model(app_label, model_name)
  File "python3.5/site-packages/django/apps/registry.py", line 207, in get_model
    return app_config.get_model(model_name, require_ready=require_ready)
  File "python3.5/site-packages/django/apps/config.py", line 170, in get_model
    "App '%s' doesn't have a '%s' model." % (self.label, model_name))
LookupError: App 'XXX' doesn't have a 'YYYY' model.
```

Not sure what's the purpose of "allow_migrate" precisely. But what's surprising is that even by calling `./manage.py migrate --database default`, the issue remains  ("default" being my SQL database)

The only solution I've come up with is to remove the salesforce router from settings.py dynamically when applying migrations...

Any idea what could cause such issue?

Thanks

**Comment by pbriet** [comment] 2019-03-15 14:43
Django  2.1.7
django-salesforce  0.8

**Comment by hynekcer** [comment] 2019-03-17 00:38
I confirm a bug, that the ModelRouter fails if a migration is applied that deletes or renames a table, even in a normal database. It was a regression by version 0.8. I'm writing a PR with a fix. Thanks for reporting.

The purpose of `allow_migrate` method is to create the right tables in the appropriate database (salesforce or non salesforce).

---
If the table has been deleted yet in models then it is more complicated (impossible without guess to determine the right database. It is possible even after the fix, if a table is created in Salesforce and recorded to migrations and dropped and recorded the migration again, then another bug is possible. It is not serious: If a SalesforceModel table is deleted then it can be fixed by editing or deleting the Salesforce migrations history. It is acceptable because Salesforce migrations are used only for faster tests of Salesforce models on a non-Salesforce database.

**Comment by pbriet** [comment] 2019-03-17 09:20
Thanks for your feedback.

**Comment by hynekcer** [comment] 2019-05-01 22:41
I prepared a fix [hynekcer/ignore-migrations](https://github.com/hynekcer/django-salesforce/commit/11cb9d017179bcb55ba68c6210bf00d26c3fc136) (temporarily on March 16), but still I need to write a test. It is not easy to write a simple test for migrations. This remains open.

**Comment by matthew-a-dunlap** [comment] 2019-05-16 20:55
Our team is running into similar issues using 0.8.0 when running our test suite, as it spins up a new database and applies all migrations.

```
  File "/Users/matthew/.virtualenvs/venv/lib/python2.7/site-packages/salesforce/router.py", line 65, in allow_migrate
    model = apps.get_model(app_label, model_name)
  File "/Users/matthew/.virtualenvs/venv/lib/python2.7/site-packages/django/apps/registry.py", line 205, in get_model
    return app_config.get_model(model_name, require_ready=require_ready)
  File "/Users/matthew/.virtualenvs/venv/lib/python2.7/site-packages/django/apps/config.py", line 172, in get_model
    "App '%s' doesn't have a '%s' model." % (self.label, model_name))
LookupError: App 'flatpages' doesn't have a 'flatpagefile' model. 
```

When I switched to the ignore-migrations branch or 0.7.2 the error does not occur.

Thank you so much for the work on this connector, it is making our non-profit group's salesforce migration much easier (https://sbgrid.org/about/what-we-do/)

**Closed** 2019-05-22 16:16 UTC
Labels: test needed

**Comment by matthew-a-dunlap** [comment] 2019-05-28 15:57
Thanks much for the new release, works great!
