### ISSUE TITLE
SF picklist fields with lots of choices not being fetched on inspectdb

### ISSUE THREAD

**Issue by lsimps204** [django-salesforce/django-salesforce#312] opened 2022-08-17 10:07 UTC
I'm having a problem while upgrading an old application using an early version of `django-salesforce` to the most recent version.

Many fields in the app fetch choices from Salesforce picklists, and display them on the UI - however, these choices appear to be truncated in the newer versions after running `inspectdb`, with this comment following the field: `# Too long choices skipped`

Is there any way around this? I've had a look at the source but I don't see any alternative that would allow the choices to be fetched, but I need to display these fields and allow users to select a valid choice.

**Comment by hynekcer** [comment] 2022-08-18 21:58
The length of picklist was restricted to 4000 characters in django-salesforce 3.2 (April 2021) because so long lines can not be edited. The idea is that two typical long picklists are countries and list of time zones. These picklist are repeated in many objects, but they should be probably shared, if they are used. The most terrible picklist is `time_zone_sid_key` approximately 33000 charactes long which is changed many times in year because counties change the Daylight Saving time on different days in Spring and Autumn.

I can make the limit configurable by settings variable `SF_MAX_INSPECTDB_PICKLIST_LENGTH`.

**Comment by hynekcer** [comment] 2022-08-19 06:00
Fixed in the main branch. I rename the issue because the word "Upgrading" is not important for other people for the most recent upgrade. I accept that this was an improvement that is also a regression.

**Comment by lsimps204** [comment] 2022-08-19 14:53
Many thanks for the quick action! I understand the rationale behind the 3.2 changes, but it's good to have the ability to configure the limit - thanks again!

**Closed** 2022-08-19 15:40 UTC
