### ISSUE TITLE
Backwards incompatible change for migrations?

### ISSUE THREAD

**Issue by jsma** [django-salesforce/django-salesforce#111] opened 2015-07-22 04:42 UTC
Just upgraded a project from Django 1.7 to 1.8 and installed 9cc56318b. When I attempted to create a new migration, I got the following error:

    django.core.exceptions.ImproperlyConfigured: SalesforceAutoField must be an auto created primary key with name 'id' (as configured by settings).

This error was not clear to me and didn't suggest any specific fix since as far as I know, the pk's *are* named 'id'. The only way I was able to resolve this error was to delete the existing initial migration and recreate it. The only significant change I could detect was going from:

    ('id', salesforce.fields.SalesforceAutoField(default=None, primary_key=True, db_column='Id', serialize=False)),

to:

    ('id', salesforce.fields.SalesforceAutoField(auto_created=True, verbose_name='ID', db_column='Id', primary_key=True, serialize=False)),

Once I edited the existing migration to change this line for each model (all created via inspectdb), the problem went away.

Was there some setting I was supposed to change along the way? Or was it expected that migrations created in 1.7 would need to be edited in place for 1.8? Either way, some note in the README would be helpful and appreciated. Thank you @philchristensen and @hynekcer for your work on this library, it has been very useful!

**Comment by hynekcer** [comment] 2015-07-22 21:28
I would like to fix it (it seems easy) but I can not reproduce it.

I can not imagine how you created a migration before django-salesforce v0.6 (9cc5631) for an app with SalesforceModel because the support was added just by v0.6. If I create the first migration with django-salesforce 0.6 and Django 1.7 then I can create the next migration also with Django 1.8. If I set `SALESFORCE_DB_ALIAS = 'default'` (in order to use a non-salesforce with SalesforceModel without explicit setting a secondary database) then I can also migrate the database.

**Comment by hynekcer** [comment] 2015-07-23 19:18
I confirm the issue. Normal models can easily create migrations with an old django-salesforce. (only some advanced features used in salesforce.testrunner.example.models require the fix introduced by v0.6)

**Comment by philchristensen** [comment] 2015-07-23 19:19
Yeah, sorry about the wontfix, it was a mistake. I hate that GitHub adds them as soon as you click, i've done this before...

**Comment by jsma** [comment] 2015-07-23 19:22
I had previously been using a pip editable install ``pip install -e git+https://github.com/django-salesforce/django-salesforce.git@1c685b3#egg=django-salesforce`` with a Django 1.7 project. I did an ``inspectdb`` at that time to get the auto-generated models (trimmed down to only the models and fields needed). I created the initial migration file from these models. This was 6 months ago or so.

I recently upgraded to Django 1.8 and installed django-salesforce https://github.com/django-salesforce/django-salesforce/commit/9cc56318ba7ac38acb55465fe601ed8d8bd3c0ee. I was only able to get rid of the error by temporarily deleting the existing migration and re-creating. The only significant change I could detect was removing the ``default = None`` and adding the ``auto_created = True`` arguments. So I only had to update the previous migration to edit the pk fields on each model and that resolved the error.

As far as the README goes, I wasn't clear whether this was a bug or an expected upgrade step but just undocumented. I also realize you haven't claimed that Django 1.8 should fully work out of the box yet so I have no right to expect it to work, just testing it and sharing my results. Thanks again for your efforts!

**Closed** 2015-07-23 21:00 UTC
Labels: discussion, question

**Comment by hynekcer** [comment] 2015-07-24 08:17
Thanks for the perfect report. The command "makemigrations" works after the fix. The change introduced by v0.6 makes the primary key compatible with Django as much as possible.

I expect that Django 1.9 or 2.0 can force a migration of our primary key again. They allow alternative primary key [UUIDField](https://docs.djangoproject.com/en/1.8/ref/models/fields/#uuidfield) in Django 1.8 instead of AutoField. If the idea will continue to consequences it can touch us. I hope that the next migration succeeds without such issues.

**Comment by hynekcer** [comment] 2015-07-24 09:23
Some problems with migrations are still possible it you migrate **to Python 3.x** and you have any migration created in v0.5x with Python 2.x. The problem is caused by many attribures encoded as byte strings in migrations created by Django with Python 2, e.g. `db_column=u'...'` that is killing for some backends (sqlite3).

If you create old migrations again with v0.6+ or with Python 3 or fix `=b'...'` and `(b'...'`, everything is OK.

**Comment by jsma** [comment] 2015-07-24 16:51
Thanks for the prompt response! Should I go ahead and use the new format in my migrations then just to guard against future issues?

    ('id', salesforce.fields.SalesforceAutoField(auto_created=True, verbose_name='ID', db_column='Id', primary_key=True, serialize=False)),

**Comment by hynekcer** [comment] 2015-07-24 18:41
No guard, you can sleep instead :-) The new format is the same. The package is now more tolerant of old formats. I was only sorry about that a new "groundles" migration of all models can be created after a new release django-salesforce for Django 1.9 or 2.0. I then have to be on guard before the release.
