### ISSUE TITLE
Issues and limitations around `select_related` usage

### ISSUE THREAD

**Issue by cooncesean** [django-salesforce/django-salesforce#175] opened 2017-03-01 20:41 UTC
## Context
We're attempting to reduce our overall network calls to SFDC. We are trying to do this by using `select_related()` to prefetch related objects associated to the model in our queryset.

## Example
For example, lets attempt to iterate over all `Opportunities` in our SFDC instance. For each `Opportunity`, print the associated opp owner (which is an `User` object). Assume the model definition below:

**models.py:**

```python
from salesforce.models import SalesforceModel

class SFDCUser(SalesforceModel):
    """Access to the SFDC `User` table."""
    username = models.CharField(max_length=80)

    class Meta(SalesforceModel.Meta):
        db_table = 'User'

class Opportunity(SalesforceModel):
    """Access to the SFDC `Opportunity` table."""
    owner = models.ForeignKey('SFDCUser', custom=False, db_column=u'OwnerId')
  
    class Meta(models.Model.Meta):
        db_table = 'Opportunity'
```

**query.py:**

```python
# Fetch each opp while joining on owner to avoid subsequent calls to 
# get owner by id for each iteration.
for opp in Opportunity.objects.all().select_related('owner'):
    print opp.owner

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-91-bdc76891f5b9> in <module>()
----> 1 for o in opp:
      2     print o
      3     print o.owner
      4

/usr/local/etc/virtualenvs/gears/local/lib/python2.7/site-packages/django/db/models/query.pyc in __iter__(self)
    256                - Responsible for turning the rows into model objects.
    257         """
--> 258         self._fetch_all()
    259         return iter(self._result_cache)
    260

/usr/local/etc/virtualenvs/gears/local/lib/python2.7/site-packages/django/db/models/query.pyc in _fetch_all(self)
   1072     def _fetch_all(self):
   1073         if self._result_cache is None:
-> 1074             self._result_cache = list(self.iterator())
   1075         if self._prefetch_related_lookups and not self._prefetch_done:
   1076             self._prefetch_related_objects()

/usr/local/etc/virtualenvs/gears/local/lib/python2.7/site-packages/salesforce/backend/query.pyc in iterator(self)
    235         """
    236         try:
--> 237             sql, params = SQLCompiler(self.query, connections[self.db], None).as_sql()
    238         except EmptyResultSet:
    239             raise StopIteration

/usr/local/etc/virtualenvs/gears/local/lib/python2.7/site-packages/salesforce/backend/compiler.pyc in as_sql(self, with_limits, with_col_aliases, subquery)
    172                     if soql_trans and re.match(r'^\w+\.\w+$', s_sql):
    173                         tab_name, col_name = s_sql.split('.')
--> 174                         s_sql = '%s.%s' % (soql_trans[tab_name], col_name)
    175                     params.extend(s_params)
    176                     out_cols.append(s_sql)

KeyError: u'Owner'
```

Perhaps I'm doing this incorrectly; perhaps a bug. Any help would be greatly appreciated :)

**Comment by philchristensen** [comment] 2017-03-01 20:57
I this issue is related to the one described in #43 ([this comment](https://github.com/django-salesforce/django-salesforce/issues/43#issuecomment-41917065)).

The [Foreign Key page](https://github.com/django-salesforce/django-salesforce/wiki/Foreign-Key-Support) on the django-salesforce wiki may be helpful to clarify things.

**Comment by hynekcer** [comment] 2017-03-01 21:37
Yes this is an important simple case that should work to can get efficiently the name of related object. I'm trying to write a simple solution with two querysets without rewriting the package, because `select_related` seems a big problem due to huge difference between Salesforce SOQL and normal SQL. I hope that an unofficial "poor man select_related" function will be ready here today. (It will be not a stable solution that can be offered by Django `select_related` queryset method. It will require a small change in your code and this issue is likely to remain open for a long time.) Thanks @philchristensen for some reference.

**Comment by cooncesean** [comment] 2017-03-01 21:59
Wow - thanks for the fast and detailed responses; awesome to see such great support for the library.

@hynekcer should I close this issue down, or are you planning to open a PR that will reference this and #43?

**Comment by philchristensen** [comment] 2017-03-02 01:29
@cooncesean can you run from Git master, or will you need a release before you can use this?

@hynekcer should this be released as 0.9.10?

**Comment by hynekcer** [comment] 2017-03-02 01:36
A temporary solution in PR #176 by a similar method `simple_select_related`. Everything is read by 2 queries. If N related fields should be resolved then N+1 queries are necessary.

replace
```
for opp in Opportunity.objects.all().select_related('owner'):
```
in your code by
```
for opp in Opportunity.objects.all().simple_select_related('owner'):
```

Read the doc string in the new method. I currently prefer error reporting if those requirements are satisfied and the related cache would work inefficiently, but later I can change it to prefer quiet cache miss later.

This is not a great support, but you have a good luck that today it is useful also for me. I could do it now or maybe... ever.

**Comment by hynekcer** [comment] 2017-03-02 02:57
@philchristensen This is the first my commit after v0.6.9 in the origin/master branch. I recommend to check my development branch https://github.com/hynekcer/django-salesforce.git@b92c5f2c2c9 that I mentioned in issues 173 and 174 recently, where is hundred times more new code after v0.6.9
The current hynekcer/development is very similar, only merged with origin/master.

I think that this issue is fixed enough to be not a big practical problem more, but still should remain open.

**Comment by cooncesean** [comment] 2017-03-02 17:13
Thanks again for jumping on this so quickly @hynekcer and for merging @philchristensen. I've pulled down master and can confirm that this is indeed working as intended - 👍 .

I can confirm that `simple_select_related` reduces API calls from "the number of results returned" O(n) to "the number of related references passed to the `simple_select_related` fcn O(1).

This is tremendously helpful guys -- thx again; this is exactly what I was looking for.

**Comment by hynekcer** [comment] 2017-03-02 17:14
Even if normal `select_related` would be fixed, there will be probably edge case where that or `simple_select_related` implementation would be the only working.

@cooncesean The issue  is accepted, however I can not reproduce your bug on so early line. (I tried it on Django 1.9 and Python 2.7 that sems your versions. The query is compiled for me without exception, and it is rejected later by SFDC, because SOQL compiled invalid.) Did you tried it really with your described model

You reduce network calls. Do you know about network request counter `salesforce.backend.driver.request_count`? (it is moved later to `salesforce.backend.dbapi.request_count`) It is used e.g. in the test for simple_select_related.

**Closed** 2017-03-02 17:16 UTC
Labels: discussion, question
