### ISSUE TITLE
Traceback during makemigrations run

### ISSUE THREAD

**Issue by nishuk0007** [django-salesforce/django-salesforce#167] opened 2016-09-21 05:10 UTC
Hello Guys, I'm facing a weired issue while running migration . I have integrated salesforce package and want to add some models at my django application. But when I run makemigrations or try to run old migration getting below error.

Django==1.9.5
django-salesforce==0.6.2.4

Please suggest me the solution.
```  
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/zorig/.virtualenvs/portal/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/zorig/.virtualenvs/portal/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/zorig/.virtualenvs/portal/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/zorig/.virtualenvs/portal/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/zorig/.virtualenvs/portal/local/lib/python2.7/site-packages/django/core/management/commands/makemigrations.py", line 106, in handle
    ProjectState.from_apps(apps),
  File "/home/zorig/.virtualenvs/portal/local/lib/python2.7/site-packages/django/db/migrations/state.py", line 174, in from_apps
    model_state = ModelState.from_model(model)
  File "/home/zorig/.virtualenvs/portal/local/lib/python2.7/site-packages/django/db/migrations/state.py", line 393, in from_model
    fields.append((name, field.clone()))
  File "/home/zorig/.virtualenvs/portal/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 464, in clone
    return self.__class__(*args, **kwargs)
  File "/home/zorig/.virtualenvs/portal/local/lib/python2.7/site-packages/salesforce/fields.py", line 197, in __init__
    related_object = args[0]
IndexError: tuple index out of range
```
Edited: Wrapped by tags for preformated text, otherwise some underscores and asterisks missed.

**Comment by hynekcer** [comment] 2016-09-21 08:19
I would like to offer some temporary solutions for your urgent case. Please explain more how you use migrations. You probably know that migrations are important with django-salesforce only if the same SalesforceModel class is used also for another type of database. People save normal Django data to other databases with `django.db.models.Model` in other directories (apps) and they use the combination of more database backends with one app usually only for easier and faster tests and not for the same persistent data in both databases. (I don't know about such case currently. I use it for some type of backup or cache, but I can create a new complete backup if the model is changed.) Most of them even run tests with sqlite3 in memory and there is really nothing to migrate. They need only to migrate application with normal Django model that use other databases for persistent data. They need only to make the changes in SalesforceModels manually in Salesforce. They run

    python manage.py makemigrations your_other_db_apps_labels ...  # not SF apps

The command "makemigrations" with SF is usually only for a convenience that other apps need not to be listed and that Salesforce migrations will be simply never used then. So, if you still have a migration for Salesforce you can rename temporary the directory `migrations` in your SF app to something different in order to avoid eventual warning (no migrations are better than obsolete migrations)

If your urgent case is that you can not create migrations for normal Django by the command above, please write it explicitly.

**Comment by hynekcer** [comment] 2016-09-21 09:48
You should run the "check" command before "makemigrations"

    python manage.py check

and you will be warned about some `ForeignKey` that `on_delete=PROTECT` or `on_delete=DO_NOTHING` must be used with SalesforceModel. (This is for one because SFDC deletes custom objects that depends on a master relationship field automatically in the cascade, for another that it would be unsafe to have two potential mechanisms that could cause cascade delete. Also some (many) builtin objects have relationships with cascade delete, that can be found in Salesforce documentation for these objects and it is usually exactly what can be expected.) If you fix the problem with "on_delete" you can run "makemigrations".

I'm writing a fix, but the best time will be with the new version 0.7. If you confirm the reason, it will be probably not optimal neither for you to have a patch for the current version 0.6.9 or to download anything special.

**Comment by hynekcer** [comment] 2016-09-22 10:45
Where is a feedback for your super super urgent issue? (24 hours after the last response) You had to confirm that it is the simple case or that is something other or that it is not urgent more. Otherwise you would wait for yourself.

**Comment by nishuk0007** [comment] 2016-09-22 11:10
@hynekcer  Sorry for the delay in response. I tried your solution by adding on_delete but no success. Still facing the issue. Thanks!

**Comment by philchristensen** [comment] 2016-09-22 12:10
@nishuk0007 You're going to need to provide some more useful information if you'd like further assistance with this issue. You still have yet to answer whether you're having the issue migrating django-salesforce models, or if it applies to all models.

Migrations for Salesforce models is a rather advanced use of the library specific to unit testing that should really only be used by people with a strong Django background. It's fairly easy to munge up migrations in Django if you don't fully understand them.

Also, in the future please do not open issues with "urgent" in the title. This is an unpaid open source project, and we do our best to answer every issue as quickly as possible.

**Comment by hynekcer** [comment] 2016-09-22 12:13
Did passed "manage.py check" without warnings? Did you also removed old migrations for models with SalesforceModel (==salesforce.models.Model) temporarily? (if you even had any) If it works then it is clear and you can restore migrations and I send a small patch.

Can you reproduce the problem on a very simplified model that can be shared? Try your models.py in a new project. You can remove all fields except `ForeignKey` and then you can remove also many classes.

**Comment by nishuk0007** [comment] 2016-09-22 12:34
Below is the current scenario, and I want to create migrations for Company model but it's giving error I posted earlier.

Also while running `manage.py check` getting below warning:
```
System check identified some issues:

WARNINGS:
contacts.Vendor.additional_contact: (fields.W340) null has no effect on ManyToManyField.

System check identified 1 issue (0 silenced).
```


```
class Company(models.Model):
    description = models.TextField(blank=True, null=True)

class Contact(models.Model):
    first_name = models.CharField(max_length=40, blank=True, default='')
    last_name = models.CharField(max_length=80)
    company = models.ForeignKey(Company,related_name='contacts')
    salesforce_id = models.CharField(max_length=255,blank=True,null=True)

    class Meta:
        verbose_name = 'Contact'
        verbose_name_plural = 'Contacts'
        managed = False
        db_table = 'authentication_user'
```

**Comment by hynekcer** [comment] 2016-09-22 13:29
- That is exactly what I wrote that you forgot "on_delete" at ForeignKey. It is a required parameter in every Django 1.9.
- The warning is related to other model not to the example. Not helpful
- The table for Contact `db_table = 'authentication_user'` is not a name of a Salesforce object. Are you sure that you can connect to Salesforce with this name?

It seems that you did not tried the simple steps in README first and you create migrations before your model works some way. (Prepare objects in Salesforce and write your first models by exporting a few objects and simplify the models by removing unused fields and especially relationships to unused objects. Then you know soon how to write valid models)

However there is a patch for version 0.6.2.4 and it should help
```
--- a/salesforce/fields.py
+++ b/salesforce/fields.py
@@ -181,10 +181,10 @@ class TimeField(SfField, models.TimeField):
 
 class ForeignKey(SfField, models.ForeignKey):
     """ForeignKey with sf_read_only attribute for Salesforce."""
-    def __init__(self, *args, **kwargs):
+    def __init__(self, to, *args, **kwargs):
         # Checks parameters before call to ancestor.
-        if DJANGO_19_PLUS and args[1:2]:
-            on_delete = args[1].__name__
+        if DJANGO_19_PLUS and args:
+            on_delete = args[0].__name__
         else:
             on_delete = kwargs.get('on_delete', models.CASCADE).__name__
         if not on_delete in ('PROTECT', 'DO_NOTHING'):
@@ -194,11 +194,10 @@ class ForeignKey(SfField, models.ForeignKey):
             # CreatedBy etc. Some related objects are deleted automatically
             # by SF even with DO_NOTHING in Django, e.g. for
             # Campaign/CampaignMember
-            related_object = args[0]
             warnings.warn("Only foreign keys with on_delete = PROTECT or "
                     "DO_NOTHING are currently supported, not %s related to %s"
-                    % (on_delete, related_object))
-        super(ForeignKey, self).__init__(*args, **kwargs)
+                    % (on_delete, to))
+        super(ForeignKey, self).__init__(to, *args, **kwargs)
 
     def get_attname(self):
         if self.name.islower():
```

Thanks for the first report. It helped me to find a real bug, because it is not sometimes easy to support unexpected inputs for more Django versions if the API is changing. Maybe we can cooperate later if you will continue studying in the meantime.

**Comment by nishuk0007** [comment] 2016-09-23 05:16
Thanks for the help.. Actually I'm in middle of the task..so I follow the steps mentioned here. and let here know if that help me. Thanks again!

**Comment by hynekcer** [comment] 2016-10-06 20:58
I will rename the issue to "makemigrations failed if ignored manage.py check" and I will close it, because that was the only reproduced case. and I think that the failed check follows from the internal logic. If you can reproduce the problem with "manage.py check" passed, please reopen the issue again.

**Closed by hynekcer** 2016-10-06 20:58 UTC
Labels: discussion, question
